### ISSUE TITLE
Set up loopback link

### ISSUE THREAD

**Issue by gabibeyer** [rootless-containers/slirp4netns#101]
Add a flag to set the loopback device link to up. This wouldn't change the default behavior, but instead if `--setup_loopback` is passed it would set the link to up. 

When modifying the order of rootless container logic in podman, runc no longer sets up the loopback device (since the netns is now being created beforehand). Seems like the best fit would be to to have that functionality in slirp4netns. Thoughts? Thank you!

**Comment by amshinde** [comment]
@gabibeyer Rather than having this as an option, I would have this as a default behaviour. slirp should make sure the loopback interface is up if it is not while configuring the network.

**Comment by AkihiroSuda** [comment]
I'm not sure this is good fit for slirp4netns.

I expect non-slirp stuff should be handled by the caller such as RootlessKit.
https://github.com/rootless-containers/rootlesskit/blob/2cb5ec5819fddecb93aeea843ecdf29d6ecaf9af/pkg/child/child.go#L134

**Comment by gabibeyer** [comment]
Thank you @AkihiroSuda, I see what you're saying! The only issue I see is if the caller doesn't enter the network namespace; it would require some sort of exec call to `nsenter ip link set lo up`. @giuseppe as a Podman (my use-case for this) maintainer, do you have a preference?

**Comment by giuseppe** [comment]
@AkihiroSuda would it be fine to be handled by `--configure`?  We already have code for setting up the network device, we can probably easily add also `lo` when the loopback device is present
