### ISSUE TITLE
Reuse existing tap setup

### ISSUE THREAD

**Issue by gabibeyer** [rootless-containers/slirp4netns#132]
In the case when a network namespace exists with an already configured tap device, spawn a slirp4netns process that re-enters the namespace, and skips the tap & network configuration aspect. This will get slirp4netns running again while using an existing network namespace.

**Comment by gabibeyer** [comment]
@AkihiroSuda Do you have a preference for going about this? 

I was looking into mounting sysfs, and checking if `/sys/class/net/<tapname>` exists, but I'm having some permission issues with mounting that. Or possibly, using iproute2 and getting the link name.

**Comment by gabibeyer** [comment]
I'm leaning towards using `getifaddrs` let me know if you think something else would be better :)

**Comment by AkihiroSuda** [comment]
Just running slirp4netns without `-c` might be fine?

**Comment by AkihiroSuda** [comment]
https://github.com/gabibeyer/slirp4netns/commit/e776a48873c352df94ce0f10d7c635fbd903f4ac is likely to break RootlessKit, which runs `ip tuntap add ...` before running `slirp4netns` (without `-c`).

https://github.com/rootless-containers/rootlesskit/blob/93164c4427c9c75aa3199b8baa5005ce9adfcd69/pkg/network/slirp4netns/slirp4netns.go#L101
https://github.com/rootless-containers/rootlesskit/blob/93164c4427c9c75aa3199b8baa5005ce9adfcd69/pkg/network/parentutils/parentutils.go#L13

**Comment by gabibeyer** [comment]
@AkihiroSuda You were right, this is not necessary! The issues I was having were podman related, and the bug [fix](https://github.com/containers/libpod/commit/6997dc14886b62c5baef50ba38ce2538ee238019) did the trick. Thank you - closing this.

**Comment by AkihiroSuda** [comment]
Do you have other feature proposals for v0.4.0 GA? 
If not I think we can release v0.4.0 after some testing

**Comment by gabibeyer** [comment]
Not that I can think of. @amshinde @egernst anything?
