### ISSUE TITLE
CAP_NET_BIND_SERVICE not working with sandbox

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/slirp4netns#135]
outside ns:
```console
$ ./slirp4netns --version
slirp4netns version 0.4.0-beta.3
commit: 179817925a6b37e8b80ba552f3998de5c4611703
$ sudo setcap cap_net_bind_service=+ep ./slirp4netns
$ ./slirp4netns --configure --mtu=65520 --disable-host-loopback $(cat /tmp/pid) tap0  --api-socket /tmp/a.sock --create-sandbox
```

inside ns:
```console
$ json='{"execute": "add_hostfwd", "arguments": {"proto": "tcp", "host_addr": "0.0.0.0", "host_port": 80, "guest_addr": "10.0.2.100", "guest_port": 80}}'
$ echo -n $json | nc -U /tmp/a.sock
{"error":{"desc":"bad request: add_hostfwd: slirp_add_hostfwd failed"}}
```

It works without `--create-sandbox`

**Comment by AkihiroSuda** [comment]
@giuseppe PTAL

**Comment by AkihiroSuda** [comment]
It seems the capability is lost when the parent process enters into userns.
Not sure how to fix the issue.

**Comment by AkihiroSuda** [comment]
@giuseppe 

Can we remove the code for keeping CAP_NET_BIND_SERVICE?

If there is a valid usecase to run slirp4netns as the real root (which wouldn't cause the userns issue), it is fine to keep CAP_NET_BIND_SERVICE, but I don't come up with any valid usecase.

**Comment by giuseppe** [comment]
isn't it required also when running in a user namespace to be able to bind ports < 1024 (like -p 8080:80)?

**Comment by AkihiroSuda** [comment]
Does libslirp bind inside the ns?

**Comment by AkihiroSuda** [comment]
Is there a valid usecase to run slirp4netns as the real root?
