### ISSUE TITLE
Building against libseccomp fails because of seccomp.h not found

### ISSUE THREAD

**Issue by saschagrunert** [rootless-containers/slirp4netns#145]
I cannot build 0.4.0 because we import seccomp.h namespaces from `libseccomp/seccomp.h`:

```
seccompfilter.c:4:10: fatal error: seccomp.h: No such file or directory
     4 | #include <seccomp.h>
       |          ^~~~~~~~~~~
```

What is the preferred way in fixing this? :innocent:

**Comment by AkihiroSuda** [comment]
https://github.com/rootless-containers/slirp4netns/pull/146
