### ISSUE TITLE
Error On make check

### ISSUE THREAD

**Issue by benyaminl** [rootless-containers/slirp4netns#154]
Hello, I don't know what's the error. Please see the file below 
[test-suite.log](https://github.com/rootless-containers/slirp4netns/files/3722559/test-suite.log)

Although I succesfully install slirp4netns, the podman can't run
ERRO[0007] error starting some container dependencies   
ERRO[0007] "error from slirp4netns while setting up port redirection: map[desc:bad request: add_hostfwd: slirp_add_hostfwd failed]" 
Error: error starting some containers: internal libpod error

**Comment by AkihiroSuda** [comment]
```
++ nsenter --preserve-credentials -U -n --target=27138 ip -json a show dev tun11
++ jq -r '.[1].addr_info[0].local'
Option "-json" is unknown, try "ip -help".
```

You need ip binary with JSON support.

Podman failure seems unrelated.

**Comment by benyaminl** [comment]
> ```
> ++ nsenter --preserve-credentials -U -n --target=27138 ip -json a show dev tun11
> ++ jq -r '.[1].addr_info[0].local'
> Option "-json" is unknown, try "ip -help".
> ```
> 
> You need ip binary with JSON support.
> 
> Podman failure seems unrelated.

How to get one?

**Comment by AkihiroSuda** [comment]
What's your distro

**Comment by benyaminl** [comment]
> What's your distro

Centos 7.7.

**Comment by AkihiroSuda** [comment]
Copy ip binary from CentOS 8 and set PATH?

**Comment by benyaminl** [comment]
> Copy ip binary from CentOS 8 and set PATH?

Let me try. Thanks! For now I'll close this first because the problem is solved and I'm doing it the worng way so it cause slrip error. I run rootless port binding on root port that slrip can't handle.

**Comment by AkihiroSuda** [comment]
`sysctl -w net.ipv4.ip_unprivileged_port_start=0` allows binding privileged ports
