### ISSUE TITLE
[wishlist] Document how to share one slirp4netns between two containers

### ISSUE THREAD

**Issue by patrakov** [rootless-containers/slirp4netns#172]
I would like to have the following setup:

1. Two or more containers, that are in the same /24 network (or maybe larger), and can communicate directly without any NAT in between (perhaps via bridged veth devices).
2. One instance of slirp4netns providing internet connection to them all, and forwarding ports to them: some to one, some to another.
3. Zero firewall rules needed on the host.

If this is possible to set up, it should be made documented and easy, and come with some push to make it the default network setup even for rootful containers.

---
My rationale for adding this wishlist entry is that I am frustrated with Docker firewalling problems in its default iptables-based setup. I don't care about rootless containers.

In particular, I recently had an "oops" moment trying to dockerize a service previously running directly on the host, that needed to be firewalled. Before dockerizing, we had a policy, "nobody except two external IPs, 10.80.88.9 and 10.80.88.10, should be able to connect to our custom service running here on port 9999", and that was easy to implement either via raw iptables (iptables-persistent on debian) or with firewalld. After dockerizing, the old iptables rules no longer have any effect, because for the kernel, it's now not the input to the host, but forwarded packets, and therefore a different chain (FORWARD, not INPUT) applies. Furthermore, both ufw and firewalld formulate FORWARD rules in terms of the forwarded-to IP and port (i.e. what's in the container), not the ones that the host presents to the outside world. But the container IP is dynamic and unknown, so it is unusable. No well-known firewall tool uses the --ctorigdstport option, even though it would make sense. And iptables-persistent cannot be used to reload the rules because it will smash the rules that Docker itself needs.

The above illustrates why I like slirp4netns: it is just a firewall-friendly process that runs on your host and listens on the port. No semantic change for the firewall comes from trying to containerize a service.

**Comment by AkihiroSuda** [comment]
You can run `ip netns` in `rootlessskit --net=slirp4netns --copy-up=/etc --copy-up=/run bash` shell.

Rootless Docker is implemented in similar way.

**Comment by muayyad-alsadi** [comment]
is this question about container to container communication within a single host? or is it cross-host communication?

**Comment by patrakov** [comment]
Single host.

**Comment by simonkrenger** [comment]
I would also like to add that this functionality would enable `podman-compose` to have multiple containers using the same port, which I think is a highly desirable feature: https://github.com/containers/podman-compose/issues/119

**Comment by tmds** [comment]
> I would also like to add that this functionality would enable podman-compose to have multiple containers using the same port, 

:+1: 

This issue is marked as 'question', should it be a 'feature request'?

**Comment by patrakov** [comment]
Yes, this is a feature request.

**Comment by AkihiroSuda** [comment]
Feature request on Podman side, question (or doc request) on slirp4netns side

https://github.com/rootless-containers/slirp4netns/issues/172#issuecomment-568778224

**Comment by AkihiroSuda** [comment]
Documented in https://github.com/rootless-containers/slirp4netns/blob/master/slirp4netns.1.md#inter-namespace-communication

**Comment by patrakov** [comment]
I confirm that the new documentation answers, from the slirp4netns side, my request. Still, a feature request for Podman (to make use of it) stays.

**Comment by tmds** [comment]
@patrakov I've created https://github.com/containers/libpod/issues/6863 for podman feature request.
