### ISSUE TITLE
Use specific outgoing IP

### ISSUE THREAD

**Issue by 5eraph** [rootless-containers/slirp4netns#173]
Hi,

I wonder whether we could/whether there would be interest in providing option to use specific outgoing IP (equivalent of `curl --interface=<IP>`). It is probably relatively rare scenario, but I could find use for it.

If I understand it correctly it should be possible in 3 steps:
* exposing `--outbound-ip=<IP>`
* ~~if above specified - create exit_fd socket which would be passed into [parent(...) function](https://github.com/rootless-containers/slirp4netns/blob/master/main.c#L254).~~
* ~~[bind(2)](http://man7.org/linux/man-pages/man2/bind.2.html) exit_fd socket to specified IP address~~
In libslirp:
* adjust [SLIRP](https://github.com/rootless-containers/slirp4netns/blob/22426511303108d2d90a6eef81c593fcc96fe527/vendor/libslirp/src/slirp.h#L123-L202) struct to hold IP for binding
* [bind(2)](http://man7.org/linux/man-pages/man2/bind.2.html) new sockets after slirp_socket calls [1](https://github.com/rootless-containers/slirp4netns/blob/bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e/vendor/libslirp/src/udp.c#L280), [2](https://github.com/rootless-containers/slirp4netns/blob/aacef69a52dfa8b3ab005f80ce1f2ec8f7e352f6/vendor/libslirp/src/ip_icmp.c#L89), [3](https://github.com/rootless-containers/slirp4netns/blob/22426511303108d2d90a6eef81c593fcc96fe527/vendor/libslirp/src/tcp_subr.c#L409) and probably [4](https://github.com/rootless-containers/slirp4netns/blob/21fdece2737dc24ffa3f01a341b8a6854f8b13b4/vendor/libslirp/src/misc.c#L72)

It should not affect incoming connections for exposed ports.

Am I right? 

_I can implement this, but I will likely need reviews/feedback to conform with your code style._

**Comment by AkihiroSuda** [comment]
SGTM, please open PR to https://gitlab.freedesktop.org/slirp/libslirp ?

**Comment by 5eraph** [comment]
I created similar issue in libslirp project, you can track it [here](https://gitlab.freedesktop.org/slirp/libslirp/issues/14).

**Comment by 5eraph** [comment]
Patches were merged into libslirp already. I should get time for slirp4net update by the end of this month :)
