### ISSUE TITLE
Consider moving --enable-sandbox out of experimental

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/slirp4netns#177]
I'm planning to release v1.0.0 by the end of the month, and I'm considering moving `--enable-{sandbox,seccomp}` out of experimental.

@giuseppe @rhatdan WDYT?

**EDIT**: seccomp will stay experimental in v1.0.0 (https://github.com/rootless-containers/slirp4netns/issues/192)

**Comment by AkihiroSuda** [comment]
Maybe we should resolve https://github.com/rootless-containers/slirp4netns/issues/116 for `--enable-sandbox`, but probably not a blocker.

**Comment by giuseppe** [comment]
I think it is a good idea, I am in favor of it.

**Comment by rhatdan** [comment]
SGTM
