### ISSUE TITLE
[question] capture network traffic in rootless container

### ISSUE THREAD

**Issue by rei-ber** [rootless-containers/slirp4netns#199]
Hi,

I already asked it at [crio channel in kubernetes slack](https://kubernetes.slack.com/archives/CAZH62UR1/p1587542405227800), where I got the information to ask my question here.

I want to know if it is possible to capture network traffic in a rootless container with tshark or tcpdump. I want to capture packets from the systems' loopback interface. My rootless user is able to run tshark/tcpdump outside a container, because I set the capabilities `cap_net_raw` and `cap_net_admin` of `/usr/bin/dumpcap` and add the rootless user to wireshark group. I thought it is possible under the condition that the root user within a container is the rootless user outside the container. So, if root within a container tries to capture network packets, the kernel knows that the syscalls to capture packets comes from the rootless user (which is able to capture) outside the container; because of uid/gid mapping. I tried it, but it did not work, so I think it is to simple to think this way?

After some research I found this documentation of [rootlesskit](https://github.com/rootless-containers/rootlesskit/blob/master/README.md#--nethost-default). It documents that tcpdump is not possible to run, if `--net=host` is used. To access loopback of systems' host, I do need to use it to run the container. So, I think this circumstance answers the first idea.

Another idea was to use iptables to redirect the traffic to a specific interface. slirp4netns creates a tap0 interface in a container (without `--net=host`). This interface is not accessible from the host. But if it were accessible, I could forward the traffic to this interface. So, is there any way to make it accessible?

Another thing is the option `--disable-host-loopback` from slirp4netns. The man page says: `prohibit connecting to 127.0.0.1:* on the host namespace`. Does it also mean, that all traffic on 127.0.0.1 which the host network namespace receives, the container network namespace does not receive? So, if I would disable the option, the container could receive all traffic which arrives at loopback at the host? It is not recommended to do this, but helpful for my understanding :)

**Comment by AkihiroSuda** [comment]
> My rootless user is able to run tshark/tcpdump outside a container, because I set the capabilities `cap_net_raw` and `cap_net_admin` of `/usr/bin/dumpcap` and add the rootless user to wireshark group. I thought it is possible under the condition that the root user within a container is the rootless user outside the container. 

You cannot. The capabilities are lost in the container because of the design of `user_namespaces(7)`.

> This interface is not accessible from the host. But if it were accessible, I could forward the traffic to this interface. So, is there any way to make it accessible?

My suggestion is to write an application that captures the packets on the host and send them to the container via a bind-mounted UNIX socket.

**Comment by AkihiroSuda** [comment]
Off-topic: if you run Rootless Docker with `DOCKERD_ROOTLESS_ROOTLESSKIT_NET=lxc-nic`,  the iptables trick should work
