### ISSUE TITLE
can `nsenter` rootless network namespace without root?

### ISSUE THREAD

**Issue by springzfx** [rootless-containers/slirp4netns#222]
`nsenter` require root to enter a namespace, even through the target namespace is a rootless network namespace.
The readme do not indicate this issue. Is there way to bypass this?

**Comment by AkihiroSuda** [comment]
nsenter -U

**Comment by AkihiroSuda** [comment]
with ` --preserve-credentials`, maybe
https://man7.org/linux/man-pages/man1/nsenter.1.html
