### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by phantomcraft** [rootless-containers/slirp4netns#23]
As I can see in the source code, slirp4netns doesn't support IPv6.

Can you implement it?

**Comment by AkihiroSuda** [comment]
PR: #25

**Comment by phantomcraft** [comment]
I tested here, the DNS address doesn't work with fe80::3 (because fe80:: is a link-local address and DNS doesn't allow it).

I edited the source and changed every fe80:: to fd00:: and worked fine.

**Comment by AkihiroSuda** [comment]
Thanks, I just blindly copy-pasted `fe80::3` from https://github.com/rd235/libslirp/blob/37fd650ad7fba7eb0360b1e1d0abf69cac6eb403/src/libslirp.c#L99

Looks like QEMU uses `fec0::3` instead, and maybe better to follow this QEMU convention?
https://github.com/qemu/qemu/blob/595123df1d54ed8fbab9e1a73d5a58c5bb71058f/net/slirp.c#L308-L361

**Comment by AkihiroSuda** [comment]
@phantomcraft @giuseppe WDYT?

**Comment by giuseppe** [comment]
merged :-)
