### ISSUE TITLE
[openSUSE Kubic] slirp4netns missing for ubuntu 

### ISSUE THREAD

**Issue by fool65c** [rootless-containers/slirp4netns#247]
It looks like slirp4netns was removed from https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/slirp4netns for everything but centos.

Is that the appropriate location for me to be pulling the from?

**Comment by AkihiroSuda** [comment]
cc @cyphar @saschagrunert

**Comment by saschagrunert** [comment]
@lsm5 who is the current maintainer of those packages? May you give it a look?

**Comment by AkihiroSuda** [comment]
https://build.opensuse.org/repositories/devel:kubic:libcontainers:stable/slirp4netns

Seems available for Debian and Ubuntu now

**Comment by lsm5** [comment]
@saschagrunert it's me for builds on OBS. Btw, would you mind giving me enough permissions here so I can assign packaging issues filed here to myself?

**Comment by lsm5** [comment]
also, it'd be great if you could create a `packaging` label.

**Comment by cyphar** [comment]
@lsm5 I've given you the "triage" role which should let you manage PRs and issues. I'm not sure why that isn't the default (or why you can't give that role to entire teams).
