### ISSUE TITLE
How to install latest version on ubuntu 20.10

### ISSUE THREAD

**Issue by mo-saeed** [rootless-containers/slirp4netns#260]
Hello,

Ubuntu package version is outdated, how to install the latest version on ubuntu 20.10 ?

Thanks

**Comment by AkihiroSuda** [comment]
Here: https://github.com/rootless-containers/slirp4netns/releases/tag/v1.1.9

**Comment by mo-saeed** [comment]
is it possible to add `latest` tag so curl can grep the latest ?

**Comment by AkihiroSuda** [comment]
add what to where?

**Comment by mo-saeed** [comment]
I want to do sth like that when I install it

```
curl -o slirp4netns --fail -L https://github.com/rootless-containers/slirp4netns/releases/download/**latest**/slirp4netns-$(uname -m)
chmod +x slirp4netns
```

**Comment by AkihiroSuda** [comment]
https://github.com/rootless-containers/slirp4netns/releases/download/latest/slirp4netns-x86_64

**Comment by mo-saeed** [comment]
I get 404

**Comment by AkihiroSuda** [comment]
Sorry https://github.com/rootless-containers/slirp4netns/releases/latest/download/slirp4netns-x86_64

**Comment by mo-saeed** [comment]
Thanks a lot @AkihiroSuda this can be closed
