### ISSUE TITLE
Request Debian to update slirp4netns package

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/slirp4netns#300]
https://packages.debian.org/sid/slirp4netns

> 1.0.1-2

@siretart Could you consider updating the package to the latest version?
v1.0.x is no longer maintained.

**Comment by siretart** [comment]
Done: https://tracker.debian.org/news/1346137/accepted-slirp4netns-120-1-source-into-unstable/

**Comment by AkihiroSuda** [comment]
Thank you!
