### ISSUE TITLE
FAIL tests/test-slirp4netns-seccomp.sh (`unshare failed: Operation not permitted`)

### ISSUE THREAD

**Issue by Catwowo** [rootless-containers/slirp4netns#303]
Executing test file :
+ nsenter --target=47418 --preserve-credentials -U -m -n true
+ sleep 0.5
+ let COUNTER=COUNTER+1
+ '[' 40 -lt 40 ']'
+ exit 1
FAIL tests/test-slirp4netns-seccomp.sh (exit status: 1)

So,I executed test-slirp4netns-seccomp.sh:
++ dirname test-slirp4netns-seccomp.sh
+ . ./common.sh
++ TEST_EXIT_CODE_SKIP=77
+ unshare -r -n sleep infinity
+ child=51656
+ wait_for_network_namespace 51656
+ COUNTER=0
+ '[' 0 -lt 40 ']'
++ nsenter_flags 51656
++ pid=51656
++ flags=--target=51656
+++ readlink /proc/51656/ns/user
unshare: unshare failed: Operation not permitted
++ userns='user:[4026531837]'
+++ readlink /proc/51656/ns/mnt
++ mntns=
+ flags=

Cat fail in test-suite.log:
unshare: unshare failed: Operation not permitted

**Comment by AkihiroSuda** [comment]
What’s your OS?
You might need to set sysctl https://rootlesscontaine.rs/getting-started/common/sysctl/

**Comment by Catwowo** [comment]
After some repetition, this error comes from my own environmental problems. I'm sorry to have taken up your time. I'm sooooooooooooooooooo sorry. Maybe you can delete this error. Thank you!!​
