### ISSUE TITLE
mention AUR package in README

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/slirp4netns#32]
https://aur.archlinux.org/packages/slirp4netns-git/

@ansemjo Thanks for creating the AUR package. Could you mention how to install the AUR pkg in README?

**Comment by ansemjo** [comment]
Sure! I have created a pull request (#33).

**Comment by ansemjo** [comment]
The AUR package is building a static binary, by the way. It's just a matter of taste for me. Are there any objections to that?

**Comment by AkihiroSuda** [comment]
+1 for static binary

**Comment by ansemjo** [comment]
Shouldn't this issue be closed then, since the pull request is merged? :)

**Comment by AkihiroSuda** [comment]
yes, thanks
