### ISSUE TITLE
Create github team for package maintainers

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/slirp4netns#69]
Creating github team would be useful for notifying important changes such as security fix and introduction of new dependencies.

---
# Core maintainers
@AkihiroSuda
@giuseppe
@cyphar 

# Package maintainers
## Fedora / Red Hat Enterprise Linux https://src.fedoraproject.org/rpms/slirp4netns
@lsm5 
@rhatdan (?)
@giuseppe (?)

## Arch Linux https://www.archlinux.org/packages/community/x86_64/slirp4netns/
@barthalion

## openSUSE / SUSE Linux Enterprise https://build.opensuse.org/package/show/openSUSE%3AFactory/slirp4netns
Unmaintained? (@cyphar ?)

## Debian GNU/Linux https://packages.debian.org/sid/slirp4netns
@siretart

## NixOS https://github.com/NixOS/nixpkgs/tree/master/pkgs/tools/networking/slirp4netns
@orivej

## Gentoo Linux https://packages.gentoo.org/packages/app-emulation/slirp4netns
@zmedico
@g-braeunlich

**Comment by cyphar** [comment]
Seems reasonable to me. @saschagrunert would probably be the right person for openSUSE maintainership (given some changes to SUSE's core containers team we are currently re-distributing which packages are maintained by whom).

**Comment by rhatdan** [comment]
SGTM

**Comment by siretart** [comment]
Agreed, I'd be happy to be added to such a team

**Comment by zmedico** [comment]
> Agreed, I'd be happy to be added to such a team

Me too!

**Comment by AkihiroSuda** [comment]
Created @rootless-containers/slirp4netns-approvers and @rootless-containers/slirp4netns-package-maintainers

Also PR https://github.com/rootless-containers/slirp4netns/pull/72 is going to add `OWNERS` file.

Let me know if there is any problem.
