### ISSUE TITLE
Document configuration

### ISSUE THREAD

**Issue by brianredbeard** [rootless-containers/slirp4netns#70]
When attempting to use `slirp4netns` with `podman` it uses the default configuration of an ip address in the range `10.0.2.0/24`.  When attempting to use this on **:cough cough:** horribly configured corporate networks it causes issues the communications between the container and resources outside of the host.  

For this reason we need documentation of how to configure the network used by `slirp4netns`, especially when consumed by utilities like `podman`.

**Comment by AkihiroSuda** [comment]
> `--cidr (since v0.3.0) specify CIDR, e.g. 10.0.2.0/24`

https://github.com/rootless-containers/slirp4netns/blob/master/slirp4netns.1.md

This should work, but not sure Podman supports setting custom `--cidr`.

**Comment by AkihiroSuda** [comment]
cc @giuseppe

**Comment by giuseppe** [comment]
no, at the moment we don't support that.  I think the best would be to allow setting it from `~/.config/containers/libpod.conf`.

@brianredbeard as a temporary workaround, you could try to override the IP address from the container, you'll need `CAP_NET_ADMIN` though.  I think it should work, I've tried:

```
podman run --rm -ti --cap-add NET_ADMIN alpine sh -c 'ip addr add 192.168.124.1 dev tap0; ip addr del 10.0.2.100 dev tap0; wget -O- google.com'
```

**Comment by AkihiroSuda** [comment]
Any suggestions for improving docs ^^

**Comment by AkihiroSuda** [comment]
I'm closing, but plz feel free to ping us to reopen
