### ISSUE TITLE
[api.c] error: ‘EXIT_FAILURE’ undeclared 

### ISSUE THREAD

**Issue by tobwen** [rootless-containers/slirp4netns#76]
I'm trying to build https://github.com/rootless-containers/slirp4netns/commit/beef37217f41ed717fbbb6ac94d778423388a7f3 on Debian 9, but I'm getting:

```
api.c:96:3: warning: incompatible implicit declaration of built-in function ‘exit’
api.c:96:3: note: include ‘<stdlib.h>’ or provide a declaration of ‘exit’
api.c:96:8: error: ‘EXIT_FAILURE’ undeclared (first use in this function)
   exit(EXIT_FAILURE);
        ^~~~~~~~~~~~
```

**Comment by tobwen** [comment]
Fix: add `#include <stdlib.h>` to `api.c`

**Comment by AkihiroSuda** [comment]
Thanks, will be fixed in https://github.com/rootless-containers/slirp4netns/pull/75
