### ISSUE TITLE
investigate how we can start using libslirp

### ISSUE THREAD

**Issue by giuseppe** [rootless-containers/slirp4netns#80]
now libslirp lives on its own repository: https://gitlab.freedesktop.org/slirp/libslirp

**Comment by AkihiroSuda** [comment]
Do you want to get this in v0.3.0 or can we defer it until QEMU upstream migrates to libslirp? (unlikely to happen until QEMU 4.1 https://lists.gnu.org/archive/html/qemu-devel/2019-03/msg07003.html )

**Comment by giuseppe** [comment]
this can happen after v0.3.0

**Comment by cyphar** [comment]
I was just about to post an issue about this. If we can use stock libslirp, from a packaging and "what is this software doing" perspective things will look much nicer. However we will need to push our patches upstream first.

I also want to look into getting LXC to be able to use slirp4netns as an alternative to their current set-uid approach (but I don't want to add a dependency to LXC which uses a forked libslirp that is statically built).

**Comment by AkihiroSuda** [comment]
I prefer to link libslirp statically for the time being so that we can experiment more optimizations (#16 #17) without dependency hell

**Comment by elmarco** [comment]
@AkihiroSuda couldn't #16 & #17 be opened in upstream libslirp instead?

Do you think we should hold back a libslirp release or is it good enough for slirp4netns in its current form?

**Comment by AkihiroSuda** [comment]
Yes, though I don't have bandwidth to look into #16 #17 deeper currently.

+1 on having releases ( https://gitlab.freedesktop.org/slirp/libslirp/issues/6 ) but not blocker for us.

**Comment by AkihiroSuda** [comment]
@giuseppe do you want to open PR for libslirp migration?

**Comment by AkihiroSuda** [comment]
opened #94 for vendoring freedesktop libslirp

**Comment by AkihiroSuda** [comment]
Merge request for moving slirp4netns patches to libslirp: https://gitlab.freedesktop.org/slirp/libslirp/merge_requests/8

@elmarco @giuseppe
