### ISSUE TITLE
Please tag a new stable release `0.3` - `podman` 1.0 needs it

### ISSUE THREAD

**Issue by r-cheologist** [rootless-containers/slirp4netns#81]
Please tag a new *stable* release `0.3`, as `podman` `1.0` was released as stable, some of it's functionality (port forwarding) needs `slirp4netns` version `>= 0.3`, the `podman` devs apparently consider `0.3` stable and packagers will be hesitant to touch non-stable.
See [here](https://github.com/containers/libpod/issues/2778) for the corresponding discussion.

**Comment by AkihiroSuda** [comment]
#82

**Comment by siretart** [comment]
uploaded to debian/experimental: https://tracker.debian.org/news/1036949/accepted-slirp4netns-030-1-source-into-experimental/

**Comment by AkihiroSuda** [comment]
@siretart thanks, but https://metadata.ftp-master.debian.org/changelogs/main/s/slirp4netns/slirp4netns_0.3.0-1_copyright seems to need to be updated

* Some files under `qemu` directory (not slirp4netns per se) were relicensed from GPL2 to BSD-3-Clause: https://github.com/rootless-containers/slirp4netns/pull/82
* `rd235_libslirp` is removed

**Comment by siretart** [comment]
Thanks for the review, will fix shortly
