### ISSUE TITLE
Allow running inside a container without creating a new namespace and get a a SLRIP-ed TAP

### ISSUE THREAD

**Issue by fabiand** [rootless-containers/slirp4netns#88]
We at KubeVirt would like to use slirp4netns.

Our use-case is to geta tap device (ideally unconfigured, and IP data in a json file), to pass this TAP to a VM in order to run the VM unprivileged, but still in a kubernetes compatible mode (just having a proces [slirp] with TCP and UDP sockets).

But today slirp4nens is cloning the net ns, and we would like to avoid this.

**Comment by fabiand** [comment]
@giuseppe @AkihiroSuda do you think this is still in scope of this project?

**Comment by fabiand** [comment]
Another option would be to have the target net namespace as a flag

**Comment by AkihiroSuda** [comment]
Does --netns-type=path work for you?

**Comment by vladikr** [comment]
Yea, this option doesn't exist in the fedora version. I can try with an upstream version later on.
@AkihiroSuda should using `--netns-type=path` avoid calling set(CLONE_NEWNET) ?

**Comment by rhatdan** [comment]
I will update fedora to v0.3.0 release

**Comment by AkihiroSuda** [comment]
Maybe we need another flag for avoiding netns issue

Cc @gabibeyer

**Comment by gabibeyer** [comment]
Passing some sort of `--netns-type=none` maybe? It could bypass the entire nsenter functionality. 
@vladikr would you want to avoid entering a user namespace as well?

**Comment by vladikr** [comment]
@gabibeyer `--netns-type=none` looks good. I think entering a user namespace isn't needed for our use case.

**Comment by giuseppe** [comment]
> @giuseppe @AkihiroSuda do you think this is still in scope of this project?

yes absolutely.  With Podman we are also working on configuring the network namespace before the container is created, something like `slirp4netns --netns-type=path /proc/PID/ns/net tap0`

Are you planning to run it in a user namespace or use it as root?

**Comment by giuseppe** [comment]
@fabiand I've opened a PR so there is no requirement for joining also the user namespace: https://github.com/rootless-containers/slirp4netns/pull/89

**Comment by fabiand** [comment]
Soooooo. Hello.

@giuseppe we'd like to have a way to skip enetering _any_ namespace  - because we are already inside a container.

@vladikr do you think your fingers can write  down a PR?
