### ISSUE TITLE
[Termux in Android] autogen.sh could not find autoreconf

### ISSUE THREAD

**Issue by arushijain71** [rootless-containers/slirp4netns#91]
While executing `./autogen.sh`, getting error

> ./autogen.sh: 2: exec: autoreconf: not found

**Comment by AkihiroSuda** [comment]
apt-get install autoconf

**Comment by arushijain45** [comment]
Thank you for your reply, now I have installed autoconf, libtool and automake, and executed `./configure --prefix=$PREFIX` but it gives following error:
> ./configure: 5294: ./configure: Syntax error: word unexpected (expecting ")")

configure [line 5294]:
PKG_CHECK_MODULES(GLIB, glib-2.0)

**Comment by AkihiroSuda** [comment]
what's your distro

**Comment by arushijain45** [comment]
Using `Termux in Android`

> uname -a
> Linux localhost 4.4.34-genymotion #4 SMP PREEMPT Mon Oct 1 15:25:53 CEST 2018 i686 Android
>

**Comment by AkihiroSuda** [comment]
I'm not familiar with that distro, but is it Debian-based? (which Debian version?)

Please try `apt install -y automake autotools-dev make gcc libglib2.0-dev`

**Comment by arushijain45** [comment]
No its not debian, I was trying it on Android mobile device using Termux but found that following packages are not available there: autotools-dev, gcc, libglib2.0-dev. But thank you for your reply.

**Comment by wlin** [comment]
same issue. any progress? thx

**Comment by AkihiroSuda** [comment]
I'm not familiar with Termux, but anyway I don't expect slirp4netns to work on Android, because Android kernel is likely to be compiled without UserNS support.

**Comment by wlin** [comment]
1. apt install pkg-config
2. edit the line PKG_CHECK_MODULES in file configure.ac (just delete the empty lines above and under it, and reenter empty line)
3. ./autogen.sh

seems it can pass this error, but meet " can't find glib2.0 "

**Comment by arushijain45** [comment]
> " can't find glib2.0 "


For this you can install glib in termux
`pkg install glib`

**Comment by wlin** [comment]
thx!
I fixed this issue after "apt install glib-dev" and "pkg install glib-2.0".

**Comment by AkihiroSuda** [comment]
Is this issue closeable? 
btw what is the usecase?

**Comment by rimassolti** [comment]
Could not auto-detect 'aclocal'; please install or specify the 'ACLOCAL' environment variable.

**Comment by parkerlreed** [comment]
Same here

```
~/evtest $ ./autogen.sh 
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal 
Can't exec "aclocal": No such file or directory at /data/data/com.termux/files/usr/share/autoconf/Autom4te/FileUtils.pm line 299.
autoreconf: error: aclocal failed with exit status: 1
```

**Comment by parkerlreed** [comment]
Found it. Part of automake
