### ISSUE TITLE
Add SPDX-License-Identifier

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/slirp4netns#95]
ref: https://github.com/kgabis/parson/pull/121

**Comment by AkihiroSuda** [comment]
https://spdx.org/licenses/

IIUC slirp4netns files are licensed under `GPL-2.0-only`, not `GPL-2.0-or-later`, is my understanding correct? @giuseppe 

(libslirp is no longer licensed under GPL2, but we still have some trivial codes that are copy-pasted from QEMU)

**Comment by giuseppe** [comment]
> [](https://spdx.org/licenses/)
> 
> IIUC slirp4netns files are licensed under `GPL-2.0-only`, not `GPL-2.0-or-later`, is my understanding correct? @giuseppe

Some slirp files are under the BSD license AFAICS, so maybe it is fine to relicense it tp gpl2+.  Where is the code coming from?

**Comment by AkihiroSuda** [comment]
> Some slirp files are under the BSD license AFAICS, so maybe it is fine to relicense it tp gpl2+.

The files under `./vendor/libslirp` must keep the original SPDX-License-Identifier.


> Where is the code coming from?

`slirp4netns.c` has some very trivial glue codes from qemu and rd235/libslirp

https://github.com/rootless-containers/slirp4netns/blob/5c690f744649ce8b37f55ce122acfba1537cc861/slirp4netns.c#L137-L223

**Comment by giuseppe** [comment]
I am not a lawyer, but I am not sure it can qualify as trivial.  At least the GNU maintainer guidelines suggest to not consider trivial something over 15 lines of code (from https://www.gnu.org/prep/maintain/maintain.html):

```

6.2 Legally Significant Changes

If a person contributes more than around 15 lines of code and/or text that is legally significant for copyright purposes, we need copyright papers for that contribution, as described above. 
```

**Comment by AkihiroSuda** [comment]
* qemu/net/slirp.c has MIT license header: https://github.com/qemu/qemu/blob/a3e3b0a7bd5de211a62cdf2d6c12b96d3c403560/net/slirp.c

* rd235/libslirp/src/qemu2libslirp.c has LGPL 2.1 (or later) license header: https://github.com/rd235/libslirp/blob/d2b7032e29f3ba98e17414b32c9effffc90f2bb0/src/qemu2libslirp.c

So probably we can choose one of:
* GPL-2.0-only
* GPL-2.0-or-later
* LGPL-2.1-only
* LGPL-2.1-or-later
